version: '3'
services:
  web:
    image: java_springv1
    build: .
    ports:
      - "8230:8230"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri2_t3_srapegnails/volumes
